# Chapter 4: Programming Fundamentals 



Let us begin with simple computations in Python using +,-,* and / operators and functions.

In [1]:
import numpy as np
import pandas as pd
import math

In [2]:
v = np.array([1,33,4,29,9,90])
gmean = (math.prod(v))**(1/len(v))
gmean

12.075621482045438

Commonly used functions like sqrt(),exp(), and log() are made available in the `math` package.

In [3]:
def geomean(v):
    gmean = (math.prod(v))**(1/len(v))
    return(gmean)

In [4]:
x = np.array([1,3,54,9,29,234,6,2,8,2456,2,8])
geomean(x)

<ipython-input-3-2c4128d2dc77>:2: RuntimeWarning: overflow encountered in long_scalars
  gmean = (math.prod(v))**(1/len(v))


5.610520874533392

In [5]:
d = np.array([2,4,63,6,3])
g = 1/d
hmean = len(d)/(np.sum(g))
hmean

3.949843260188088

In [6]:
def harmean(v):
  a = 1/v
  hmean = len(v)/(np.sum(a))
  return(hmean)

In [7]:
v = np.array([2,23,3456,1,4,6])
geomean(v)

12.500396862365385

In [8]:
harmean(v)

3.0605463611219847

In [9]:
v = np.array([4,6,23,6,375,9])
cutoff = 6
vsub = v[v>cutoff]
vsub

array([ 23, 375,   9])

In [10]:
len(vsub)

3

In [11]:
def vecsize(v, cutoff = 1):
  vsub = v[v>cutoff]
  return(len(vsub))

In [12]:
v = np.array([.2,5,2,.6,3,57,34,5])
vecsize(v,10)

2

In [13]:
vecsize(v)

6

In [14]:
vec1 = np.array([2,2,6,3,546,2346,22,34,7,21,4])
cutoff1 = 5
cutoff2 = 100 
vsub = vec1[(vec1>cutoff1) & (vec1<cutoff2)]
vsub

array([ 6, 22, 34,  7, 21])

In [15]:
def intermediate (vec1, cutoff1, cutoff2):
  vsub = vec1[(vec1>cutoff1) & (vec1<cutoff2)]
  return(vsub)

vec1 = np.array([2,2,6,3,546,2346,22,34,7,21,4])
intermediate(vec1,5,100)

array([ 6, 22, 34,  7, 21])

In [16]:
def intermediate (vec1, cutoff1, 
                           cutoff2):
  vsub = vec1[(vec1>cutoff1) & 
             (vec1<cutoff2)]
  return(vsub)

vec1 = np.array(
     [2,2,6,3,546,2346,22,34,7,21,4])
intermediate(vec1,5,100)

array([ 6, 22, 34,  7, 21])

In [17]:
student = pd.read_csv("../data/student.csv")
f1 = (student['gender']==0) & (student['prog']==3) & (student['math']>60)
f1

0      False
1      False
2      False
3      False
4      False
       ...  
309    False
310    False
311    False
312    False
313    False
Length: 314, dtype: bool

In [18]:
x3 = student[f1]
print(x3.head())

       id  gender  math  prog  daysabs
88   1089       0    84     3        4
164  2007       0    71     3        0
166  2009       0    71     3        0
168  2011       0    77     3        2
172  2015       0    65     3        1


## Factor Variables

In [19]:
arthritis = pd.read_csv("../data/Arthritis.csv")
arthritis.head()

Unnamed: 0  ID Treatment   Sex  Age Improved
0           1  57   Treated  Male   27     Some
1           2  46   Treated  Male   29     None
2           3  77   Treated  Male   30     None
3           4  17   Treated  Male   32   Marked
4           5  36   Treated  Male   46   Marked

In [20]:
arthritis['Sex'].value_counts()

Female    59
Male      25
Name: Sex, dtype: int64

In [21]:
arthritis[['Treatment','Improved']].value_counts().unstack()

Improved   Marked  None  Some
Treatment                    
Placebo         7    29     7
Treated        21    13     7

In [22]:
arthritis[['Treatment','Improved']].value_counts(normalize=True).unstack()

Improved     Marked      None      Some
Treatment                              
Placebo    0.083333  0.345238  0.083333
Treated    0.250000  0.154762  0.083333

In [23]:
arthritis.groupby('Improved')['Treatment'].value_counts(normalize=True).unstack()

Treatment   Placebo   Treated
Improved                     
Marked     0.250000  0.750000
None       0.690476  0.309524
Some       0.500000  0.500000

In [24]:
arthritis.groupby('Treatment')['Improved'].value_counts(normalize=True).unstack()

Improved     Marked      None      Some
Treatment                              
Placebo    0.162791  0.674419  0.162791
Treated    0.512195  0.317073  0.170732

In [25]:
df3 = arthritis[['Sex','Treatment','Improved']].value_counts().unstack()[['None','Some','Marked']]
df3

Improved          None  Some  Marked
Sex    Treatment                    
Female Placebo    19.0   7.0     6.0
       Treated     6.0   5.0    16.0
Male   Placebo    10.0   NaN     1.0
       Treated     7.0   2.0     5.0

In [26]:
#df4 = df3.reset_index(level='Improved')
#display(df4)
df4 = df3.unstack()
df4

Improved     None            Some          Marked        
Treatment Placebo Treated Placebo Treated Placebo Treated
Sex                                                      
Female       19.0     6.0     7.0     5.0     6.0    16.0
Male         10.0     7.0     NaN     2.0     1.0     5.0

## Numeric Variables

In [27]:
whiteside = pd.read_csv('../data/whiteside.csv',index_col=0)
whiteside.head()

Temp  Gas
Insul            
Before  -0.8  7.2
Before  -0.7  6.9
Before   0.4  6.4
Before   2.5  6.0
Before   2.9  5.8

In [28]:
whiteside.groupby(['Insul'])['Temp'].agg(np.mean)

Insul
After     4.463333
Before    5.350000
Name: Temp, dtype: float64

In [29]:
whiteside.groupby(['Insul'])['Temp'].mean()

Insul
After     4.463333
Before    5.350000
Name: Temp, dtype: float64

## Conditionals

***Conditional Statements***

In [30]:
v = np.array([1,2,3,4])
if sum(v) == 10:
    print("Yes, the sum is 10.")

Yes, the sum is 10.


In [31]:
v1 = np.array([1,2,3,3])
if sum(v) == 10:
    print("Yes, the sum is 10.")
else:
    print("No, the sum is not 10.") 

Yes, the sum is 10.


***Conditional Expressions***

In [32]:
v1 = np.array([2,36,83,2,5,7,2,9,3,12])
v2 = np.where(v1>=5,1,0)
print(v2)

[0 1 1 0 1 1 0 1 0 1]


In [33]:
whiteside = pd.read_csv('../data/whiteside.csv')
whiteside.head()

Insul  Temp  Gas
0  Before  -0.8  7.2
1  Before  -0.7  6.9
2  Before   0.4  6.4
3  Before   2.5  6.0
4  Before   2.9  5.8

In [34]:
whiteside['hotcold'] = np.where(whiteside['Temp']<5, "cold", "hot")
whiteside.head()

Insul  Temp  Gas hotcold
0  Before  -0.8  7.2    cold
1  Before  -0.7  6.9    cold
2  Before   0.4  6.4    cold
3  Before   2.5  6.0    cold
4  Before   2.9  5.8    cold

In [35]:
x = whiteside.groupby(['Insul','hotcold'])['Gas'].mean().reset_index()
x

Insul hotcold      Gas
0   After    cold  3.88500
1   After     hot  2.68000
2  Before    cold  5.94000
3  Before     hot  4.00625

In [36]:
x.columns

Index(['Insul', 'hotcold', 'Gas'], dtype='object')

In [37]:
x.rename(columns={'Insul':'Insulation','hotcold':'Weather','Gas':'Average_Gas_Consumption'}, inplace=True)
x

Insulation Weather  Average_Gas_Consumption
0      After    cold                  3.88500
1      After     hot                  2.68000
2     Before    cold                  5.94000
3     Before     hot                  4.00625

# Looping

***For Loops***

In [38]:
for i in range (1, 11):
    print (i)

1
2
3
4
5
6
7
8
9
10


In [39]:
for i in range (1,11):
    print (i*(i-1)*(i-2))

0
0
6
24
60
120
210
336
504
720


In [40]:
v1 = np.array([1,4,5,2,4,6,7,8,9,12,4,1,5,2])
v2 = v1
for i in range (2,len(v1)+1):
    v2[i-1]=v2[i-2]+v1[i-1]
v1

array([ 1,  5, 10, 12, 16, 22, 29, 37, 46, 58, 62, 63, 68, 70])

In [41]:
import sympy
ans = np.array([])
a = 20
b = 30
for i in range (a,b+1):
    if sympy.isprime(i):
        ans = np.append(ans,i)
ans

array([23., 29.])

***Avoiding Loops with Vectorization***

In [42]:
x = np.arange(20,30+1)
y = sympy.isprime(x)
y

False

In [43]:
total = 0
v = np.array([1,4,2,5,73,4,5])
for i in range (len(v)-1):
    total = total + (v[i]*v[i+1])
total

699

In [44]:
v1 = v[:(len(v)-1)] 
v2 = v[1:len(v)]
total = sum(v1*v2) 
total

699

In [45]:
v1 = np.array([72,3,57,2,8,24,7])
v2 = np.array([])
n = len(v1)
for i in range (n):
    v2 = np.append(v2,v1[n-1-i])
v2

array([ 7., 24.,  8.,  2., 57.,  3., 72.])

***While Loops***

In [46]:
startnumber = 300
numprimes = 3
i = startnumber + 1
primi = 0
primevec = np.array([])
while primi<numprimes:
    if sympy.isprime(i):
        primi = primi+1
        primevec = np.append(primevec,i)
    i = i+1
print(primevec)

[307. 311. 313.]


In [47]:
def nextprimes(startnumber, numprimes):
    primi = 0
    i = startnumber + 1
    primevec = np.array([])
    while primi<numprimes:
        if sympy.isprime(i):
            primi = primi+1
            primevec = np.append(primevec,i)
        i = i+1
    return(print(primevec))
nextprimes(3,3)

[ 5.  7. 11.]


In [48]:
nextprimes(19,10)

[23. 29. 31. 37. 41. 43. 47. 53. 59. 61.]


In [49]:
nextprimes(9,3)

[11. 13. 17.]
