# Chapter 4: Programming Fundamentals 



Let us begin with simple computations in Python using +,-,* and / operators and functions.

In [39]:
import numpy as np
import pandas as pd
import math

In [40]:
v = np.array([1,33,4,29,9,90])
gmean = (math.prod(v))**(1/len(v))
gmean

12.075621482045438

Commonly used functions like sqrt(),exp(), and log() are made available in the `math` package.

In [41]:
def geomean(v):
    gmean = (math.prod(v))**(1/len(v))
    return(gmean)

In [42]:
x = np.array([1,3,54,9,29,234,6,2,8,2456,2,8])
geomean(x)

<ipython-input-41-2c4128d2dc77>:2: RuntimeWarning: overflow encountered in long_scalars
  gmean = (math.prod(v))**(1/len(v))


5.610520874533392

In [43]:
d = np.array([2,4,63,6,3])
g = 1/d
hmean = len(d)/(np.sum(g))
hmean

3.949843260188088

In [44]:
def harmean(v):
  a = 1/v
  hmean = len(v)/(np.sum(a))
  return(hmean)

In [45]:
v = np.array([2,23,3456,1,4,6])
geomean(v)

12.500396862365385

In [46]:
harmean(v)

3.0605463611219847

In [47]:
v = np.array([4,6,23,6,375,9])
cutoff = 6
vsub = v[v>cutoff]
vsub

array([ 23, 375,   9])

In [48]:
len(vsub)

3

In [49]:
def vecsize(v, cutoff = 1):
  vsub = v[v>cutoff]
  return(len(vsub))

In [50]:
v = np.array([.2,5,2,.6,3,57,34,5])
vecsize(v,10)

2

In [51]:
vecsize(v)

6

In [52]:
vec1 = np.array([2,2,6,3,546,2346,22,34,7,21,4])
cutoff1 = 5
cutoff2 = 100 
vsub = vec1[(vec1>cutoff1) & (vec1<cutoff2)]
vsub

array([ 6, 22, 34,  7, 21])

In [53]:
def intermediate (vec1, cutoff1, cutoff2):
  vsub = vec1[(vec1>cutoff1) & (vec1<cutoff2)]
  return(vsub)

vec1 = np.array([2,2,6,3,546,2346,22,34,7,21,4])
intermediate(vec1,5,100)

array([ 6, 22, 34,  7, 21])

In [54]:
def intermediate (vec1, cutoff1, 
                           cutoff2):
  vsub = vec1[(vec1>cutoff1) & 
             (vec1<cutoff2)]
  return(vsub)

vec1 = np.array(
     [2,2,6,3,546,2346,22,34,7,21,4])
intermediate(vec1,5,100)

array([ 6, 22, 34,  7, 21])

In [55]:
student = pd.read_csv("../data/student.csv")
f1 = (student['gender']==0) & (student['prog']==3) & (student['math']>60)
f1

0      False
1      False
2      False
3      False
4      False
       ...  
309    False
310    False
311    False
312    False
313    False
Length: 314, dtype: bool

In [56]:
x3 = student[f1]
print(x3.head())

       id  gender  math  prog  daysabs
88   1089       0    84     3        4
164  2007       0    71     3        0
166  2009       0    71     3        0
168  2011       0    77     3        2
172  2015       0    65     3        1


## Factor Variables

In [57]:
arthritis = pd.read_csv("../data/Arthritis.csv")
arthritis.head()

Unnamed: 0  ID Treatment   Sex  Age Improved
0           1  57   Treated  Male   27     Some
1           2  46   Treated  Male   29     None
2           3  77   Treated  Male   30     None
3           4  17   Treated  Male   32   Marked
4           5  36   Treated  Male   46   Marked

In [58]:
arthritis['Sex'].value_counts()

Female    59
Male      25
Name: Sex, dtype: int64

In [59]:
arthritis[['Treatment','Improved']].value_counts().unstack()

Improved   Marked  None  Some
Treatment                    
Placebo         7    29     7
Treated        21    13     7

In [60]:
arthritis[['Treatment','Improved']].value_counts(normalize=True).unstack()

Improved     Marked      None      Some
Treatment                              
Placebo    0.083333  0.345238  0.083333
Treated    0.250000  0.154762  0.083333

In [61]:
arthritis.groupby('Improved')['Treatment'].value_counts(normalize=True).unstack()

Treatment   Placebo   Treated
Improved                     
Marked     0.250000  0.750000
None       0.690476  0.309524
Some       0.500000  0.500000

In [62]:
arthritis.groupby('Treatment')['Improved'].value_counts(normalize=True).unstack()

Improved     Marked      None      Some
Treatment                              
Placebo    0.162791  0.674419  0.162791
Treated    0.512195  0.317073  0.170732

In [63]:
df3 = arthritis[['Sex','Treatment','Improved']].value_counts().unstack()[['None','Some','Marked']]
df3

Improved          None  Some  Marked
Sex    Treatment                    
Female Placebo    19.0   7.0     6.0
       Treated     6.0   5.0    16.0
Male   Placebo    10.0   NaN     1.0
       Treated     7.0   2.0     5.0

In [64]:
#df4 = df3.reset_index(level='Improved')
#display(df4)
df4 = df3.unstack()
df4

Improved     None            Some          Marked        
Treatment Placebo Treated Placebo Treated Placebo Treated
Sex                                                      
Female       19.0     6.0     7.0     5.0     6.0    16.0
Male         10.0     7.0     NaN     2.0     1.0     5.0

## Numeric Variables

In [65]:
whiteside = pd.read_csv('../data/whiteside.csv',index_col=0)
whiteside.head()

Temp  Gas
Insul            
Before  -0.8  7.2
Before  -0.7  6.9
Before   0.4  6.4
Before   2.5  6.0
Before   2.9  5.8

In [66]:
whiteside.groupby(['Insul'])['Temp'].agg(np.mean)

Insul
After     4.463333
Before    5.350000
Name: Temp, dtype: float64

In [67]:
whiteside.groupby(['Insul'])['Temp'].mean()

Insul
After     4.463333
Before    5.350000
Name: Temp, dtype: float64

## Conditionals

***Conditional Statements***

In [68]:
v = np.array([1,2,3,4])
if sum(v) == 10:
    print("Yes, the sum is 10.")

Yes, the sum is 10.


In [69]:
v1 = np.array([1,2,3,3])
if sum(v) == 10:
    print("Yes, the sum is 10.")
else:
    print("No, the sum is not 10.") 

Yes, the sum is 10.


***Conditional Expressions***

In [70]:
v1 = np.array([2,36,83,2,5,7,2,9,3,12])
v2 = np.where(v1>=5,1,0)
print(v2)

[0 1 1 0 1 1 0 1 0 1]


In [71]:
whiteside = pd.read_csv('../data/whiteside.csv')
whiteside.head()

Insul  Temp  Gas
0  Before  -0.8  7.2
1  Before  -0.7  6.9
2  Before   0.4  6.4
3  Before   2.5  6.0
4  Before   2.9  5.8

In [72]:
whiteside['hotcold'] = np.where(whiteside['Temp']<5, "cold", "hot")
whiteside.head()

Insul  Temp  Gas hotcold
0  Before  -0.8  7.2    cold
1  Before  -0.7  6.9    cold
2  Before   0.4  6.4    cold
3  Before   2.5  6.0    cold
4  Before   2.9  5.8    cold

In [73]:
x = whiteside.groupby(['Insul','hotcold'])['Gas'].mean()
x

Insul   hotcold
After   cold       3.88500
        hot        2.68000
Before  cold       5.94000
        hot        4.00625
Name: Gas, dtype: float64

In [74]:
y = pd.DataFrame(x).columns
y

Index(['Gas'], dtype='object')

In [75]:
y.columns = ["Insulation","Weather", "Average_Gas_Consumption"]
y

Index(['Gas'], dtype='object')